using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Diagnostics;
using System.Linq;

namespace FooProject.Generator
{
    /// <summary>
    /// ソースコードを生成するためにつかうクラス
    /// </summary>
    /// <remarks>
    /// Flags属性の付いたEnumに指定するとコードを生成することができる
    /// </remarks>
    [AttributeUsage(AttributeTargets.Enum, AllowMultiple = false, Inherited = false)]
    public sealed class BigRleArrayFlagsAttribute : Attribute
    {
        public string GeneratedClassName { get; private set; }

        /// <summary>
        /// コンストラクター
        /// </summary>
        /// <remarks>何も指定しない場合はEnumのクラス名＋Collectionという名前になります</remarks>
        public BigRleArrayFlagsAttribute()
        {
            this.GeneratedClassName = string.Empty;
        }

        /// <summary>
        /// コンストラクター
        /// </summary>
        /// <param name="generatedClassName">生成したいコレクションクラス名</param>
        public BigRleArrayFlagsAttribute(string generatedClassName)
        {
            this.GeneratedClassName = generatedClassName;
        }
    }

    [Generator(LanguageNames.CSharp)]
    public class EnumWithFlagsGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
//ジェネレーターのデバック用
#if false
            if (!Debugger.IsAttached)
            {
                Debugger.Launch();
            }
#endif 
            var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            "FooProject.Generator.BigRleArrayFlagsAttribute",
                static (node, token) =>
                {
                    token.ThrowIfCancellationRequested();
                    return node.IsKind(SyntaxKind.EnumDeclaration);
                },
                static (ctx, token) =>
                {
                    token.ThrowIfCancellationRequested();
                    var classDeclaration = (EnumDeclarationSyntax)ctx.TargetNode;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

                    bool hasAttr = symbol.GetAttributes().Any(attr =>attr.AttributeClass?.Name == "FlagsAttribute");
                    if (hasAttr == false)
                        return null;

                    return symbol;
                }
                );

            context.RegisterSourceOutput(source, Emit);
        }

        private void Emit(SourceProductionContext context, INamedTypeSymbol typeSymbol)
        {
            if (typeSymbol == null)
                return;

            // 名前空間を考える。partialクラスで定義するので同じ名前空間にする
            var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace ? "" : $"namespace {typeSymbol.ContainingNamespace};";

            //コレクションクラスの名前を取得する
            string collectionSymbolName = string.Empty;
            var attributeData = typeSymbol.GetAttributes().Where((data)=> {
                return data.AttributeClass.Name == "BigRleArrayFlagsAttribute";
            }).FirstOrDefault();
            if(attributeData != null)
            {
                var overridenNameOpt =
                    attributeData.NamedArguments.SingleOrDefault(kvp => kvp.Key == "generatedClassName").Value;
                if (overridenNameOpt.IsNull)
                {
                    if (attributeData.ConstructorArguments.Length == 1)
                        overridenNameOpt = attributeData.ConstructorArguments[0];
                }
                var targetTypeSymbolName = overridenNameOpt.IsNull ? typeSymbol.Name + "Collection" : overridenNameOpt.Value.ToString();
                collectionSymbolName = targetTypeSymbolName;
            }
            else
            {
                collectionSymbolName = typeSymbol.Name + "Collection";
            }

            // ソースを考える
            var code =
                $$"""
    // <auto-generated/>
    using FooProject.Collection;

    {{ns}}

    public class {{collectionSymbolName}}
    {
        BigRleArray<{{typeSymbol.Name}}> collection = new BigRleArray<{{typeSymbol.Name}}>();

        public void Add({{typeSymbol.Name}} m,int length)
        {
            collection.AddRange(m, length);
        }

        public {{typeSymbol.Name}} Get(long index)
        {
            return ({{typeSymbol.Name}})collection.GetValue(index);
        }

        public void Set(int index,int count, {{typeSymbol.Name}} value)
        {
            collection.UpdateRange(index, value, count, (container, require_count, inputed_item) =>
            {
                var new_value = container.Value | inputed_item.Value;
                return new BigRleArrayRange<{{typeSymbol.Name}}>(new_value, require_count); 
            });
        }

        public void Unset(int index, int count, {{typeSymbol.Name}} value)
        {
            collection.UpdateRange(index, value, count, (container, require_count, inputed_item) =>
            {
                var new_value = {{typeSymbol.Name}}.None;
                if (value != {{typeSymbol.Name}}.None)
                    new_value = container.Value ^ inputed_item.Value;
                return new BigRleArrayRange<{{typeSymbol.Name}}>(new_value, require_count);
            });
        }

        public IEnumerable<IRleArrayRange<{{typeSymbol.Name}}>> GetRanges(int index,int count)
        {
             return collection.GetRangesAndClamp(index, count);
        }

    }
    """;

            // ファイル名に使う
            var fullType = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", "")
                .Replace("<", "_")
                .Replace(">", "_");

            // 拡張子はg.csとする
            context.AddSource($"{fullType}.{collectionSymbolName}.EnumWithFlagsGenerator.g.cs", code);
        }
    }
}
