using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FooProject.Generator
{
    /// <summary>
    /// ソースコードを生成するためにつかうクラス
    /// </summary>
    /// <remarks>
    /// Flags属性の付いたEnumに指定するとコードを生成することができる
    /// </remarks>
    [AttributeUsage(AttributeTargets.Enum, AllowMultiple = false, Inherited = false)]
    public sealed class BigRleArrayFlagsAttribute : Attribute
    {
    }

    [Generator(LanguageNames.CSharp)]
    public class EnumWithFlagsGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var source = context.SyntaxProvider.ForAttributeWithMetadataName(
                "FooProject.Generator.BigRleArrayFlagsAttribute",
                static (node, token) =>
                {
                    return node.IsKind(SyntaxKind.EnumDeclaration);
                },
                static (ctx, token) =>
                {
                    var classDeclaration = (EnumDeclarationSyntax)ctx.TargetNode;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

                    bool hasAttr = symbol.GetAttributes().Any(attr =>attr.AttributeClass?.Name == "FlagsAttribute");
                    if (hasAttr == false)
                        return null;

                    return symbol;
                }
                );

            context.RegisterSourceOutput(source, Emit);
        }

        private void Emit(SourceProductionContext context, INamedTypeSymbol typeSymbol)
        {
            // 名前空間を考える。partialクラスで定義するので同じ名前空間にする
            var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace ? "" : $"namespace {typeSymbol.ContainingNamespace};";

            // ソースを考える
            var code =
                $$"""
    // <auto-generated/>
    using FooProject.Collection;

    {{ns}}

    public class {{typeSymbol.Name}}Collection
    {
        BigRleArray<{{typeSymbol.Name}}> collection = new BigRleArray<{{typeSymbol.Name}}>();

        public void Add({{typeSymbol.Name}} m,int length)
        {
            collection.AddRange(m, length);
        }

        public {{typeSymbol.Name}} Get(long index)
        {
            return ({{typeSymbol.Name}})collection.GetValue(index);
        }

        public void Set(int index,int count, {{typeSymbol.Name}} value)
        {
            collection.UpdateRange(index, value, count, (container, require_count, inputed_value) =>
            {
                var new_value = container.Value | inputed_value;
                return new BigRleArrayRange<{{typeSymbol.Name}}>(new_value, require_count); 
            });
        }

        public void Unset(int index, int count, {{typeSymbol.Name}} value)
        {
            collection.UpdateRange(index, value, count, (container, require_count, inputed_value) =>
            {
                var new_value = {{typeSymbol.Name}}.None;
                if (value != {{typeSymbol.Name}}.None)
                    new_value = container.Value ^ inputed_value;
                return new BigRleArrayRange<{{typeSymbol.Name}}>(new_value, require_count);
            });
        }

        public IEnumerable<IRleArrayRange<{{typeSymbol.Name}}>> GetRanges(int index,int count)
        {
             return collection.GetRangesAndClamp(index, count);
        }

    }
    """;

            // ファイル名に使う
            var fullType = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", "")
                .Replace("<", "_")
                .Replace(">", "_");

            // 拡張子はg.csとする
            context.AddSource($"{fullType}.EnumWithFlagsGenerator.g.cs", code);
        }
    }
}
